# Feature Engineering and Encoding

In [1]:
import pandas as pd
from category_encoders import TargetEncoder

# Load cleaned datasets
train_df = pd.read_csv('/home/heisenberg_0702/Housing-Pricing-Regression/data/processed/cleaning_train_data.csv')
test_df = pd.read_csv('/home/heisenberg_0702/Housing-Pricing-Regression/data/processed/cleaning_test_data.csv')
holdout_df = pd.read_csv('/home/heisenberg_0702/Housing-Pricing-Regression/data/processed/cleaning_holdout_data.csv')

# Print date ranges for verification
print("Train Date Range:", train_df['date'].min(), "to", train_df['date'].max())
print("Test Date Range:", test_df['date'].min(), "to", test_df['date'].max())
print("Holdout Date Range:", holdout_df['date'].min(), "to", holdout_df['date'].max())

# Ensure datetime format
train_df['date'] = pd.to_datetime(train_df['date'])
test_df['date'] = pd.to_datetime(test_df['date'])
holdout_df['date'] = pd.to_datetime(holdout_df['date'])

Train Date Range: 2012-03-31 to 2019-12-31
Test Date Range: 2020-01-31 to 2021-12-31
Holdout Date Range: 2022-01-31 to 2023-12-31

In [3]:
# Funtion to add date features
def add_date_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add separate date features to the dataframe from the 'date' column. 
    Features added: year, month, quarter
    """
    df['year'] = df['date'].dt.year
    df['month'] = df['date'].dt.month
    df['quarter'] = df['date'].dt.quarter

    df.insert(1, 'year', df.pop('year'))
    df.insert(2, 'month', df.pop('month'))
    df.insert(3, 'quarter', df.pop('quarter'))

    return df

# Apply date feature addition
train_df = add_date_features(train_df)
test_df = add_date_features(test_df)
holdout_df = add_date_features(holdout_df)

In [8]:
# See all columns and first few rows
pd.set_option('display.max_columns', None)

In [10]:
# Train set preview
print(train_df.shape)
train_df.head(1)

(585199, 43)

,date,year,month,quarter,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full,lat,lng
0,2012-03-31,2012,3,1,46550.0,217450.0,31.813674,110.183666,14.0,23.0,44.0,64.0,59.5,0.943662,0.142857,0.043478,ATL,30002,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,200773.999557,"Atlanta-Sandy Springs-Roswell, GA",33.7338,-84.3922

In [11]:
# Test set preview
print(test_df.shape)
test_df.head(1)

(149423, 43)

,date,year,month,quarter,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full,lat,lng
0,2020-01-31,2020,1,1,184000.0,168450.0,123.333333,109.8998,35.0,30.0,34.0,37.0,50.0,0.954732,0.171429,0.3,CHI,60482,3.0,0.0,2.0,0.0,68.0,30.0,60.0,5.0,14.0,10849.0,42.1,27037.0,10795.0,4598.0,964.0,169000.0,5690.0,414.0,10573.0,10573.0,5089.0,164839.734849,"Chicago-Naperville-Elgin, IL-IN",41.6675,-87.9597

In [12]:
# Holdout set preview
print(holdout_df.shape)
holdout_df.head(1)

(148943, 43)

,date,year,month,quarter,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full,lat,lng
0,2022-01-31,2022,1,1,340000.0,349999.0,189.867865,195.526649,282.0,287.0,241.0,73.0,12.0,0.991177,0.308511,0.634146,ORL,32771,9.0,0.0,1.0,1.0,56.0,64.0,18.0,4.0,9.0,57074.0,37.7,33896.0,56681.0,22246.0,1289.0,261800.0,29485.0,1469.0,55621.0,55621.0,24381.0,314667.746005,"Orlando-Kissimmee-Sanford, FL",28.4343,-81.363